# Generated by Django 3.1.7 on 2021-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Image', models.ImageField(upload_to='uploads/')),
                ('description', models.CharField(max_length=400)),
                ('capacity', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
